### ISSUE TITLE
[graph-vis] Make the IoK prettier

### ISSUE THREAD

**Issue by rustielin** [indexofknowledge/iok#10]
CSS or something

**Comment by rustielin** [comment]
Update: with more data points, the `dagre` layout gets a bit out of hand, since at least as of now, the IoK seems to be pretty bushy. (e.g. dependencies not too expansive yet). We can have non-downward-facing arrows if needed, esp since we highlight dependencies already, but it might look a bit strange

**Comment by rianadon** [comment]
Idea: We can put all of the information inside of the circle, so that when you click it the graph zooms in like Prezi.

**Comment by rustielin** [comment]
@rianadon yea that seems pretty good. Maybe we can hack apart the "compound" nodes feature? https://cytoscape.org/cytoscape.js-cola/demo-compound.html

Also might be a problem when a resource is a resource for more than one topic node. Maybe we could programmatically enforce that...

**Comment by rustielin** [comment]
Also: change the styling for resource nodes as big IoKs can get pretty messy
